spring:
  application:
    name: springboot-starter

  datasource:
    url: jdbc:postgresql://localhost:5432/springboot_starter
    username: postgres
    password: Trustno1

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

server:
  port: 3000
