services:
  redis:
    image: redis:7.4.0
    container_name: ganatan-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data

  redis-insight:
    image: redis/redisinsight:latest
    container_name: ganatan-redis-insight
    ports:
      - "5540:5540"
    depends_on:
      - redis

volumes:
  redis_data: