spring:
  application:
    name: springboot-starter

  datasource:
    url: jdbc:postgresql://localhost:5432/backend_crud
    username: postgres
    password: Trustno1
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true

server:
  port: 3000