quarkus.application.name=quarkus-starter
quarkus.http.port=3000

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=Trustno1
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/backend_crud

quarkus.hibernate-orm.schema-management.strategy=validate
quarkus.hibernate-orm.log.sql=true

%test.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/backend_crud_test